### PR TITLE
allow regress out for scale data

### PR DESCRIPTION
**Pull request by derrik-gratz**

### CODE REVIEW

**Comment by derrik-gratz** [comment]
The function was tested as stand alone and worked, but suspiciously running `runIntegration` with the regress.out arg set didn't change the resulting integrated object in any discernable way, so need to see if when the function is added to the package, if the internal calls will change. I'm suspicious the internal calls to `FindNormVar..` were not using the environment function definition, so they didn't have the change, hence no CC regression. If not, then somehow cc regression didn't affect the integration at all, which seems unlikely

**Comment by derrik-gratz** [comment]
pushing this since it's a one-liner, has been tested, and is somewhat time sensitive. All the other changes are just documentation

**Comment by micahpf** [comment]
Oh wow, I was literally just trying to open the same exact PR, lol. Thanks.

**Comment by derrik-gratz** [comment]
actually, I realized there was another scaledata call in runIntegration / runHarmony, need to patch that too really quick

**Comment by derrik-gratz** [comment]
#56 
Not sure If I could have reopened this? oh well

**Comment by micahpf** [comment]
Oh good catch! That just saved me a headache.

**Comment by micahpf** [comment]
> #56
> Not sure If I could have reopened this? oh well

Yeah I think technically that would have been better.

**Pull request merged**
